# client ->(HTTP/1.1)->
#   server1
#   server2
#   ...
#   serverN
#

---
kind: Namespace
apiVersion: v1
metadata:
  name: burn-http
  annotations:
    config.linkerd.io/proxy-log-level: linkerd=info,warn
    config.linkerd.io/proxy-version: ver-backpressure-debug-lock-2020-02-11.0
    linkerd.io/inject: enabled

#
# client
#
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: client
  namespace: burn-http
  labels:
    app: client

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: client
  name: client-serial
  namespace: burn-http
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      serviceAccount: client
      containers:
      - image: buoyantio/slow_cooker:latest
        name: client
        args:
        - http://server/

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: client
  name: client-burst
  namespace: burn-http
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      serviceAccount: client
      containers:
      - image: buoyantio/slow_cooker:latest
        name: client
        args:
        - -concurrency
        - 100
        - http://server/

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: client
  name: client-empty
  namespace: burn-http
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: client
    spec:
      serviceAccount: client
      containers:
      - image: buoyantio/slow_cooker:latest
        name: client
        args:
        - http://empty/#$i

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: client
  name: client-unbound
  namespace: burn-http
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: client
    spec:
      serviceAccount: client
      containers:
      - image: buoyantio/bb:v0.0.5
        name: client
        args:
        - http://unbound/#$i


#
# server
#

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
  namespace: burn-http
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccount: server
      containers:
      - image: buoyantio/bb:v0.0.5
        name: bb
        command:
        - "/bin/bash"
        args:
        - "-c"
        - |
          /out/bb terminus --h1-server-port=7070 --response-text=""
        ports:
        - containerPort: 7070
          name: http
        - containerPort: 7711
          name: unbound

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: server
  namespace: burn-http
  labels:
    app: server
---
kind: Service
apiVersion: v1
metadata:
  name: server
  namespace: burn-http
  labels:
    app: server
spec:
  selector:
    app: server
  ports:
  - port: 80
    targetPort: http
    name: http
---
kind: Service
apiVersion: v1
metadata:
  name: unbound
  namespace: burn-http
  labels:
    app: server
spec:
  selector:
    app: server
  ports:
  - port: 80
    targetPort: unbound
    name: http
---
kind: Service
apiVersion: v1
metadata:
  name: empty
  namespace: burn-http
  labels:
    app: server
spec:
  selector:
    app: empty
  ports:
  - port: 80
    targetPort: http
    name: http


