
---
kind: Namespace
apiVersion: v1
metadata:
  name: burn-http
  annotations:
    config.linkerd.io/proxy-version: ver-backpressure-2020-03-01.0
    linkerd.io/inject: enabled

#
# client
#
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: client
  namespace: burn-http
  labels:
    app: client

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client-serial
  namespace: burn-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      client: serial
  template:
    metadata:
      labels:
        app: client
        client: serial
    spec:
      serviceAccount: client
      containers:
      - image: buoyantio/slow_cooker:latest
        name: client
        command:
        - /bin/sh
        args:
        - -c
        - |-
          set -eu
          sleep 20
          while true ; do
            for t in $((RANDOM % 60)) ; do
              c=$((1 + (RANDOM % 100)))
              n=$((c * (RANDOM % 100)))
              q=$((RANDOM % 100))
              echo "sending $n reqs; concurrency=$c; rps=$q"
              /slow_cooker/slow_cooker -concurrency $c -qps $q -totalRequests $n http://middle/
              echo "sleeping ${t}s"
              sleep $t
            done
          done

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client-burst
  namespace: burn-http
spec:
  replicas: 0
  selector:
    matchLabels:
      app: client
      client: burst
  template:
    metadata:
      labels:
        app: client
        client: burst
    spec:
      serviceAccount: client
      containers:
      - image: buoyantio/slow_cooker:latest
        name: client
        args:
        - -concurrency=100
        - http://server/

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client-empty
  namespace: burn-http
spec:
  replicas: 0
  selector:
    matchLabels:
      app: client
      client: empty
  template:
    metadata:
      labels:
        app: client
        client: empty
    spec:
      serviceAccount: client
      containers:
      - image: buoyantio/slow_cooker:latest
        name: client
        args:
        - http://empty/#$i

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client-unbound
  namespace: burn-http
spec:
  replicas: 0
  selector:
    matchLabels:
      app: client
      client: unbound
  template:
    metadata:
      labels:
        app: client
        client: unbound
    spec:
      serviceAccount: client
      containers:
      - image: buoyantio/bb:v0.0.5
        name: client
        args:
        - http://unbound/#$i


#
# middle
#

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: middle
  name: middle
  namespace: burn-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middle
  template:
    metadata:
      labels:
        app: middle
      #annotations:
      #  config.linkerd.io/proxy-log-level: "linkerd=trace,debug,linkerd2_proxy_transport=debug,linkerd2_metrics=warn,linkerd2_http_metrics=warn,tokio_reactor=warn"
    spec:
      serviceAccount: middle
      containers:
      - image: buoyantio/bb:v0.0.5
        name: bb
        command:
        - "/bin/bash"
        args:
        - "-c"
        - |
          /out/bb point-to-point-channel --h1-server-port=7070 --grpc-downstream-server=server:81
        ports:
        - containerPort: 7070
          name: http

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: middle
  namespace: burn-http
  labels:
    app: middle
---
kind: Service
apiVersion: v1
metadata:
  name: middle
  namespace: burn-http
  labels:
    app: middle
spec:
  selector:
    app: middle
  ports:
  - port: 80
    targetPort: http
    name: http

#
# server
#

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
  namespace: burn-http
spec:
  replicas: 20
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccount: server
      containers:
      - image: buoyantio/bb:v0.0.5
        name: bb
        command:
        - "/bin/bash"
        args:
        - "-c"
        - |
          /out/bb terminus --h1-server-port=7070 --grpc-server-port=7071 --response-text=""
        ports:
        - containerPort: 7070
          name: http
        - containerPort: 7071
          name: grpc
        - containerPort: 7711
          name: unbound

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: server
  namespace: burn-http
  labels:
    app: server
---
kind: Service
apiVersion: v1
metadata:
  name: server
  namespace: burn-http
  labels:
    app: server
spec:
  selector:
    app: server
  ports:
  - port: 80
    targetPort: http
    name: http
  - port: 81
    targetPort: grpc
    name: grpc
---
kind: Service
apiVersion: v1
metadata:
  name: unbound
  namespace: burn-http
  labels:
    app: server
spec:
  selector:
    app: server
  ports:
  - port: 80
    targetPort: unbound
    name: http
---
kind: Service
apiVersion: v1
metadata:
  name: empty
  namespace: burn-http
  labels:
    app: server
spec:
  selector:
    app: empty
  ports:
  - port: 80
    targetPort: http
    name: http


