---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scaler
  annotations:
    linkerd.io/inject: disabled
  name: scaler
  namespace: burn-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaler
  template:
    metadata:
      labels:
        app: scaler
    spec:
      serviceAccount: scaler
      containers:
      - image: lachlanevenson/k8s-kubectl:v1.15.9
        name: scaler
        command:
        - /bin/sh
        args:
        - -c
        - |-
          sleep 20
          while true; do
            kubectl -n burn-http rollout restart deploy/server
            t=$(( RANDOM % 60 ))
            echo "sleeping for ${t}s"
            sleep $t
          done

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: scaler
  namespace: burn-http
  labels:
    app: scaler
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: scaler
  namespace: burn-http
  labels:
    app: scaler
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "patch", "update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: scaler
  namespace: burn-http
  labels:
    app: scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scaler
subjects:
- kind: ServiceAccount
  name: scaler

